// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tksmith/burning.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Burning struct {
	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Timestamp int32  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Amount    int32  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Creator   string `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Burning) Reset()         { *m = Burning{} }
func (m *Burning) String() string { return proto.CompactTextString(m) }
func (*Burning) ProtoMessage()    {}
func (*Burning) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa541c62e3ed764, []int{0}
}
func (m *Burning) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Burning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Burning.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Burning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Burning.Merge(m, src)
}
func (m *Burning) XXX_Size() int {
	return m.Size()
}
func (m *Burning) XXX_DiscardUnknown() {
	xxx_messageInfo_Burning.DiscardUnknown(m)
}

var xxx_messageInfo_Burning proto.InternalMessageInfo

func (m *Burning) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Burning) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Burning) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Burning) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Burning)(nil), "supsidacdisaac.ds.tksmith.Burning")
}

func init() { proto.RegisterFile("tksmith/burning.proto", fileDescriptor_aaa541c62e3ed764) }

var fileDescriptor_aaa541c62e3ed764 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x4e, 0x03, 0x31,
	0x10, 0x45, 0xd7, 0x40, 0x12, 0xc5, 0xa5, 0x05, 0xc8, 0x48, 0xc8, 0x8a, 0xa8, 0xd2, 0xec, 0xba,
	0xa0, 0xa7, 0xc8, 0x11, 0x52, 0x21, 0x3a, 0xaf, 0x6d, 0x25, 0x16, 0xf2, 0x8e, 0xe5, 0x19, 0x4b,
	0xe1, 0x16, 0x1c, 0x8b, 0x32, 0x25, 0x25, 0xda, 0xbd, 0x08, 0xc2, 0x49, 0x44, 0xf9, 0x66, 0xbe,
	0xbe, 0xde, 0xe7, 0x77, 0xf4, 0x8e, 0x31, 0xd0, 0x5e, 0xf7, 0x25, 0x0f, 0x61, 0xd8, 0x75, 0x29,
	0x03, 0x81, 0x78, 0xc0, 0x92, 0x30, 0x38, 0x63, 0x5d, 0x40, 0x63, 0x6c, 0xe7, 0xb0, 0x3b, 0x07,
	0x9f, 0x80, 0x2f, 0x36, 0xa7, 0xac, 0xb8, 0xe5, 0xb3, 0x30, 0x38, 0x7f, 0x90, 0x6c, 0xc5, 0xd6,
	0xcb, 0xed, 0x09, 0xc4, 0x23, 0x5f, 0x52, 0x88, 0x1e, 0xc9, 0xc4, 0x24, 0xaf, 0x56, 0x6c, 0x3d,
	0xdb, 0xfe, 0x1f, 0xc4, 0x3d, 0x9f, 0x9b, 0x08, 0x65, 0x20, 0x79, 0x5d, 0x5f, 0x67, 0x12, 0x92,
	0x2f, 0x6c, 0xf6, 0x86, 0x20, 0xcb, 0x9b, 0xda, 0x76, 0xc1, 0xcd, 0xeb, 0xd7, 0xa8, 0xd8, 0x71,
	0x54, 0xec, 0x67, 0x54, 0xec, 0x73, 0x52, 0xcd, 0x71, 0x52, 0xcd, 0xf7, 0xa4, 0x9a, 0xb7, 0x97,
	0x5d, 0xa0, 0x7d, 0xe9, 0x3b, 0x0b, 0x51, 0x57, 0xe1, 0xf6, 0xcf, 0xb8, 0xad, 0xca, 0xda, 0x02,
	0x46, 0xc0, 0xd6, 0x21, 0x65, 0x9f, 0x92, 0xd1, 0x0e, 0xf5, 0x41, 0x5f, 0xd6, 0xd2, 0x47, 0xf2,
	0xd8, 0xcf, 0xeb, 0xd8, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xc0, 0xc6, 0x7a, 0x05,
	0x01, 0x00, 0x00,
}

func (m *Burning) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Burning) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Burning) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBurning(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i = encodeVarintBurning(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if m.Timestamp != 0 {
		i = encodeVarintBurning(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintBurning(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBurning(dAtA []byte, offset int, v uint64) int {
	offset -= sovBurning(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Burning) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovBurning(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovBurning(uint64(m.Timestamp))
	}
	if m.Amount != 0 {
		n += 1 + sovBurning(uint64(m.Amount))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBurning(uint64(l))
	}
	return n
}

func sovBurning(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBurning(x uint64) (n int) {
	return sovBurning(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Burning) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBurning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Burning: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Burning: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBurning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBurning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBurning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBurning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBurning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBurning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBurning(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBurning
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBurning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBurning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBurning
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBurning
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBurning
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBurning        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBurning          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBurning = fmt.Errorf("proto: unexpected end of group")
)
