// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ds/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetSignalRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetSignalRequest) Reset()         { *m = QueryGetSignalRequest{} }
func (m *QueryGetSignalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSignalRequest) ProtoMessage()    {}
func (*QueryGetSignalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f71ed5ce232deb, []int{0}
}
func (m *QueryGetSignalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSignalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSignalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSignalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSignalRequest.Merge(m, src)
}
func (m *QueryGetSignalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSignalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSignalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSignalRequest proto.InternalMessageInfo

func (m *QueryGetSignalRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetSignalResponse struct {
	Signal Signal `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal"`
}

func (m *QueryGetSignalResponse) Reset()         { *m = QueryGetSignalResponse{} }
func (m *QueryGetSignalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSignalResponse) ProtoMessage()    {}
func (*QueryGetSignalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f71ed5ce232deb, []int{1}
}
func (m *QueryGetSignalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSignalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSignalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSignalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSignalResponse.Merge(m, src)
}
func (m *QueryGetSignalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSignalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSignalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSignalResponse proto.InternalMessageInfo

func (m *QueryGetSignalResponse) GetSignal() Signal {
	if m != nil {
		return m.Signal
	}
	return Signal{}
}

type QueryAllSignalRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSignalRequest) Reset()         { *m = QueryAllSignalRequest{} }
func (m *QueryAllSignalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSignalRequest) ProtoMessage()    {}
func (*QueryAllSignalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f71ed5ce232deb, []int{2}
}
func (m *QueryAllSignalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSignalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSignalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSignalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSignalRequest.Merge(m, src)
}
func (m *QueryAllSignalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSignalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSignalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSignalRequest proto.InternalMessageInfo

func (m *QueryAllSignalRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSignalResponse struct {
	Signal     []Signal            `protobuf:"bytes,1,rep,name=signal,proto3" json:"signal"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSignalResponse) Reset()         { *m = QueryAllSignalResponse{} }
func (m *QueryAllSignalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSignalResponse) ProtoMessage()    {}
func (*QueryAllSignalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f71ed5ce232deb, []int{3}
}
func (m *QueryAllSignalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSignalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSignalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSignalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSignalResponse.Merge(m, src)
}
func (m *QueryAllSignalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSignalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSignalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSignalResponse proto.InternalMessageInfo

func (m *QueryAllSignalResponse) GetSignal() []Signal {
	if m != nil {
		return m.Signal
	}
	return nil
}

func (m *QueryAllSignalResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetSignalRequest)(nil), "supsidacdisaac.ds.ds.QueryGetSignalRequest")
	proto.RegisterType((*QueryGetSignalResponse)(nil), "supsidacdisaac.ds.ds.QueryGetSignalResponse")
	proto.RegisterType((*QueryAllSignalRequest)(nil), "supsidacdisaac.ds.ds.QueryAllSignalRequest")
	proto.RegisterType((*QueryAllSignalResponse)(nil), "supsidacdisaac.ds.ds.QueryAllSignalResponse")
}

func init() { proto.RegisterFile("ds/query.proto", fileDescriptor_52f71ed5ce232deb) }

var fileDescriptor_52f71ed5ce232deb = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x6b, 0x14, 0x31,
	0x14, 0xc7, 0x27, 0xab, 0x5d, 0x68, 0x04, 0x85, 0xb0, 0x8a, 0x2c, 0x65, 0x2c, 0x73, 0x58, 0x8b,
	0x3a, 0x09, 0xad, 0x27, 0xbd, 0xb5, 0x07, 0x7b, 0xd5, 0xa9, 0x27, 0x2f, 0x92, 0x99, 0x84, 0x18,
	0x98, 0x4e, 0xd2, 0x7d, 0x19, 0x69, 0x11, 0x2f, 0x7e, 0x00, 0x11, 0x7a, 0xf6, 0x2b, 0xf8, 0x39,
	0x7a, 0x2c, 0x78, 0xf1, 0x24, 0xb2, 0xeb, 0x07, 0x91, 0x49, 0x82, 0x6e, 0x77, 0x87, 0x55, 0x2f,
	0x43, 0x26, 0xbc, 0xff, 0xff, 0xfd, 0xde, 0xfb, 0xcf, 0xe0, 0x9b, 0x02, 0xd8, 0x49, 0x2b, 0xa7,
	0x67, 0xd4, 0x4e, 0x8d, 0x33, 0x64, 0x04, 0xad, 0x05, 0x2d, 0x78, 0x25, 0x34, 0x70, 0x5e, 0x51,
	0x01, 0x54, 0xc0, 0x78, 0x4b, 0x19, 0xa3, 0x6a, 0xc9, 0xb8, 0xd5, 0x8c, 0x37, 0x8d, 0x71, 0xdc,
	0x69, 0xd3, 0x40, 0xd0, 0x8c, 0x1f, 0x54, 0x06, 0x8e, 0x0d, 0xb0, 0x92, 0x83, 0x0c, 0x66, 0xec,
	0xed, 0x6e, 0x29, 0x1d, 0xdf, 0x65, 0x96, 0x2b, 0xdd, 0xf8, 0xe2, 0x58, 0x7b, 0x4b, 0x00, 0x03,
	0xad, 0x1a, 0x5e, 0xc7, 0x8b, 0x91, 0x32, 0xca, 0xf8, 0x23, 0xeb, 0x4e, 0xe1, 0x36, 0xcb, 0xf1,
	0xed, 0x17, 0x9d, 0xd1, 0xa1, 0x74, 0x47, 0xbe, 0xba, 0x90, 0x27, 0xad, 0x04, 0x47, 0x46, 0x78,
	0x43, 0x37, 0x42, 0x9e, 0xde, 0x45, 0xdb, 0x68, 0x67, 0xb3, 0x08, 0x2f, 0xd9, 0x4b, 0x7c, 0x67,
	0xb9, 0x1c, 0xac, 0x69, 0x40, 0x92, 0xa7, 0x78, 0x18, 0xda, 0x79, 0xc1, 0x8d, 0xbd, 0x2d, 0xda,
	0x37, 0x20, 0x0d, 0xaa, 0x83, 0xeb, 0x17, 0xdf, 0xef, 0x25, 0x45, 0x54, 0x64, 0xaf, 0x23, 0xc4,
	0x7e, 0x5d, 0x5f, 0x85, 0x78, 0x86, 0xf1, 0x9f, 0xc1, 0xa2, 0xf1, 0x84, 0x86, 0x2d, 0xd0, 0x6e,
	0x0b, 0x34, 0xac, 0x34, 0x6e, 0x81, 0x3e, 0xe7, 0x4a, 0x46, 0x6d, 0xb1, 0xa0, 0xcc, 0x3e, 0xa3,
	0xc8, 0xbd, 0xd0, 0xa1, 0x87, 0xfb, 0xda, 0xff, 0x71, 0x93, 0xc3, 0x2b, 0x78, 0x03, 0x8f, 0x77,
	0xff, 0xaf, 0x78, 0xa1, 0xf1, 0x22, 0xdf, 0xde, 0x97, 0x01, 0xde, 0xf0, 0x7c, 0xe4, 0x1c, 0xe1,
	0x61, 0xe8, 0x45, 0x1e, 0xf6, 0x93, 0xf4, 0xc6, 0x35, 0x7e, 0xf4, 0x6f, 0xc5, 0xa1, 0x77, 0x46,
	0x3f, 0x7c, 0xfd, 0x79, 0x3e, 0xd8, 0x21, 0x13, 0xe6, 0x55, 0x79, 0x27, 0xcb, 0xbd, 0x8e, 0x09,
	0x60, 0xbf, 0xbf, 0x1c, 0xf6, 0xce, 0xa7, 0xfe, 0x9e, 0x7c, 0x44, 0x78, 0x33, 0x58, 0xec, 0xd7,
	0xeb, 0xc1, 0x96, 0x23, 0x5c, 0x0b, 0xb6, 0x92, 0x46, 0x36, 0xf1, 0x60, 0xdb, 0x24, 0x5d, 0x0f,
	0x76, 0x70, 0x74, 0x31, 0x4b, 0xd1, 0xe5, 0x2c, 0x45, 0x3f, 0x66, 0x29, 0xfa, 0x34, 0x4f, 0x93,
	0xcb, 0x79, 0x9a, 0x7c, 0x9b, 0xa7, 0xc9, 0xab, 0x27, 0x4a, 0xbb, 0x37, 0x6d, 0x49, 0x2b, 0x73,
	0xbc, 0xea, 0x11, 0xa2, 0xc9, 0x05, 0xb8, 0xa9, 0xb4, 0x96, 0x77, 0x86, 0xa7, 0xdd, 0xc3, 0x9d,
	0x59, 0x09, 0xe5, 0xd0, 0xff, 0x12, 0x8f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x9d, 0xbb,
	0x48, 0xab, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a signal by index.
	Signal(ctx context.Context, in *QueryGetSignalRequest, opts ...grpc.CallOption) (*QueryGetSignalResponse, error)
	// Queries a list of signal items.
	SignalAll(ctx context.Context, in *QueryAllSignalRequest, opts ...grpc.CallOption) (*QueryAllSignalResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Signal(ctx context.Context, in *QueryGetSignalRequest, opts ...grpc.CallOption) (*QueryGetSignalResponse, error) {
	out := new(QueryGetSignalResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.ds.ds.Query/Signal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SignalAll(ctx context.Context, in *QueryAllSignalRequest, opts ...grpc.CallOption) (*QueryAllSignalResponse, error) {
	out := new(QueryAllSignalResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.ds.ds.Query/SignalAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a signal by index.
	Signal(context.Context, *QueryGetSignalRequest) (*QueryGetSignalResponse, error)
	// Queries a list of signal items.
	SignalAll(context.Context, *QueryAllSignalRequest) (*QueryAllSignalResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Signal(ctx context.Context, req *QueryGetSignalRequest) (*QueryGetSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (*UnimplementedQueryServer) SignalAll(ctx context.Context, req *QueryAllSignalRequest) (*QueryAllSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.ds.ds.Query/Signal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Signal(ctx, req.(*QueryGetSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SignalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SignalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.ds.ds.Query/SignalAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SignalAll(ctx, req.(*QueryAllSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supsidacdisaac.ds.ds.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signal",
			Handler:    _Query_Signal_Handler,
		},
		{
			MethodName: "SignalAll",
			Handler:    _Query_SignalAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ds/query.proto",
}

func (m *QueryGetSignalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSignalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSignalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSignalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSignalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSignalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Signal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSignalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSignalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSignalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSignalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSignalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSignalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signal) > 0 {
		for iNdEx := len(m.Signal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetSignalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSignalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Signal.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSignalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSignalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Signal) > 0 {
		for _, e := range m.Signal {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetSignalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSignalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSignalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSignalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSignalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSignalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Signal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSignalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSignalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSignalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSignalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSignalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSignalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signal = append(m.Signal, Signal{})
			if err := m.Signal[len(m.Signal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
